######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:38:11 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex2.h MyLabel.h
FORMS += ex2.ui
SOURCES += ex2.cpp main.cpp MyLabel.cpp
