######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:42:05 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex5.h MyLabel.h
FORMS += ex5.ui
SOURCES += ex5.cpp main.cpp MyLabel.cpp
