######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:47:01 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex8.h MyQTextEdit.h
FORMS += ex8.ui
SOURCES += ex8.cpp main.cpp myqtextedit.cpp
