######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:50:02 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex10.h MyQLineEdit.h
FORMS += ex10.ui
SOURCES += ex10.cpp main.cpp MyQLineEdit.cpp
