######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:46:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex7.h MyLabel.h
FORMS += ex7.ui
SOURCES += ex7.cpp main.cpp MyLabel.cpp
