######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:39:29 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex3.h MyLabel.h
FORMS += ex3.ui
SOURCES += ex3.cpp main.cpp MyLabel.cpp
