######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:40:18 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex4.h MyLabel.h
FORMS += ex4.ui
SOURCES += ex4.cpp main.cpp MyLabel.cpp
