######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:18:28 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex1.h MyQLCDNumber.h
FORMS += ex1.ui
SOURCES += ex1.cpp main.cpp MyQLCDNumber.cpp
