######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:44:36 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex6.h MyQLCDNumber.h MySlider.h
FORMS += ex6.ui
SOURCES += ex6.cpp main.cpp MyQLCDNumber.cpp MySlider.cpp
