######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:21:26 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += examen.h myqlcdnumber.h
FORMS += examen.ui
SOURCES += examen.cpp main.cpp myqlcdnumber.cpp
