######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 13:48:02 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex9.h MyQLCDNumber.h
FORMS += ex9.ui
SOURCES += ex9.cpp main.cpp MyQLCDNumber.cpp
